networks:
  default:
    driver: bridge
    name: roboshop
    #external: true #if you already created network using docker network create command
volumes:
  mongodb:
  redis:
  mysql:
  rabbitmq:
services:
  mongodb:
    image: khizar111/mongodb:v1
    container_name: mongodb
    volumes:
    - mongodb: /data/db
  catalogue:
    image: khizar111/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: redis:7.0  #here we are directly running redis images from docker hub, bcz we ar enot loading anything in redis
    container_name: redis
    volumes:
    - redis: /data
  user:
    image: khizar111/user:v1
    container_name: user
    depends_on: 
    - redis
    - mongodb
  cart: 
    image: khizar111/cart:v1
    container_name: cart
    depends_on:
    - redis
    - catalogue
  mysql:
    image: khizar111/mysql:v1
    container_name: mysql
    volumes:
    - mysql: /var/lib/mysql
  shipping:
    image: khizar111/shipping:v1
    container_name: shipping
    depends_on: 
    - cart
    - mysql     
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    volumes:
    - rabbitmq: /var/lib/rabbitmq    
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123      
  payment:
    image: khizar111/payment:v1
    container_name: payment
    environment:
      CART_HOST: cart
      CART_PORT: 8080
      USER_HOST: user
      USER_PORT: 8080
      AMQP_HOST: rabbitmq
      AMQP_USER: roboshop
      AMQP_PASS: roboshop123    
    depends_on:
    - cart
    - user
    - rabbitmq
  frontend:
    image: khizar111/frontend:v1
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
    - payment